### ISSUE TITLE
broccoli build directory already exists

### ISSUE THREAD

**Issue by Globegitter** [broccolijs/broccoli-cli#4]
When I try to run `broccoli build xxx` and the folder already exists I am getting this error:
 
![screen shot 2014-06-24 at 11 17 06](https://cloud.githubusercontent.com/assets/2580254/3370328/94174626-fb8e-11e3-9879-d342239aa34f.png)

Seems to me like it should just overwrite files, right?

**Comment by joliss** [comment]
Broccoli intentionally doesn't have `--force` option - see my comment at https://github.com/broccolijs/broccoli/pull/225#issuecomment-84625203.
