### ISSUE TITLE
Wacky error behaviour

### ISSUE THREAD

**Issue by jasonkuhrt** [broccolijs/broccoli-cli#5]
this might be related to #3.

I tried running `broccoli serve` but I did something wrong in my setup. `broccoli` promptly began repeating an error message ad infinitum. I had to close the terminal window and start a new session from scratch.

![screen shot 2014-07-04 at 2 11 06 pm](https://cloud.githubusercontent.com/assets/284476/3484332/d10736a2-03a6-11e4-9fb1-1bd37d4d7e31.png)

Clearly this should not happen, will discourage newcomers, etc.

**Comment by lynndylanhurley** [comment]
I'm having the same issue. I've been at this for several hours and I can't figure out what the problem even is. Are the docs out of date or something?

@jasonkuhrt - did you figure out what was causing the original error?

**Comment by jasonkuhrt** [comment]
I haven't used Broccoli for months and don't plan to use it again. Sorry!

**Comment by lynndylanhurley** [comment]
Thx, I came to that same conclusion today. What did you end up using?

**Comment by joliss** [comment]
I believe this is fixed in Broccoli 0.13.4 (2c30cf53169db9cadb8596ea8b56c11c1c247554). I'll go ahead and close this - if anyone sees more problems of this sort, let me know and I can reopen.
