### ISSUE TITLE
Rebuild in a directory

### ISSUE THREAD

**Issue by billybonks** [broccolijs/broccoli-cli#9]
Currently `broccoli serve` will host the built tree on a web server. I need it to be built in a directory. Is there any support for this? I am currently achieving this functionality using bash scripts and `broccoli build`.

**Comment by zzeniou86** [comment]
check `broccoli-timepiece`

**Comment by billybonks** [comment]
ye i found it after a while. im not sure why it needs to be a separate project in all honesty.

**Comment by stefanpenner** [comment]
broccoli master supports this, the next release will include it.

**Comment by billybonks** [comment]
nice :), I think in the latest broccoli build that I had I used fswatch to rebuild the directory when files changed. closing then 👍
